### ISSUE TITLE
[BUG] Reboot and Login

### ISSUE THREAD

**Issue by kkm** [Eltion/Instagram-SSL-Pinning-Bypass#29]
Nox Player works well but if after the restart you have to log out and log in again so that burp proxy works again.
happened to you too? always registering again after a restart?

**Comment by Eltion** [comment]
@kkm this is because the instagram is using HTTP/3. There is already an issue for this here https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/19

A temporary solution for this is to delete the config file that instagram creates, I've added a function for this but it's commented for now, to enable it just uncomment this line:
```patch
- //disableHTTP3();
+ disableHTTP3();
```
